    repos:
      - repo: https://github.com/commitizen-tools/commitizen
        rev: v4.10.0 # Use the latest stable version of Commitizen
        hooks:
          - id: commitizen
            stages: [commit-msg]
